spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: stockMonitoring
      username: admin
      password: admin123
  database:
    type: mongodb
  debezium:
    engine:
      name: mongodb-engine
      connector-class: io.debezium.connector.mongodb.MongoDbConnector
      offset-storage: org.apache.kafka.connect.storage.FileOffsetBackingStore
      offset-storage-file-filename: offsets.dat
      offset-flush-interval-ms: 60000
      mongodb:
        hosts: localhost:27017
        user: admin
        password: admin123
        auth-source: admin
        database-include-list: stockMonitoring
        collection-include-list: instrument_identity
        server-name: mongodb-instance
        poll-interval-ms: 1000
        snapshot-mode: initial
      database-history: io.debezium.relational.history.FileDatabaseHistory
      database-history-file-filename: /tmp/mongodb-dbhistory.dat